### ISSUE TITLE
Update the Bg image of Card

### ISSUE THREAD

**Issue by Vidhanvyrs** [Vidhanvyrs/WeatherApp#3]
want to update the Bg image of the card to the relevant weather Any ideas!!
check Card.css for the update

**Comment by 0m3ga13** [comment]
in cards.css create three classes:
```css
.sunny {
  background-image: url("images/weather2.jpg");
}

.cloudy {
  background-image: url("images/weather.jpg");
}

.rainy {
  background-image: url("images/weather3.jpg");
} 
```

back to your MainCard.js do the following:
1- create an empty String backgroundClass
2- give the backgroundClass a value according the temperatures (sunny,cloudy,rainy), you have the ifs already inplace
3- in your card div do the following:             <div className={`card ${backgroundClass}`} key={index}>


```javascript
// your code
          let backgroundClass = "";
// your code 
 if (temperatureCelsius > 35) {
            message = "🌞";
            backgroundClass = "sunny";
            // imgSrc = "images/weather.jpg";
          } else if (temperatureCelsius > 10 && temperatureCelsius < 35) {
            message = "⛅";
            backgroundClass = "cloudy";
            // imgSrc = "images/weather2.jpg";
          } else {
            message = "❄";
            backgroundClass = "rainy";
            // imgSrc = "images/weather3.jpg";
          }
          //your code 

            <div className={`card ${backgroundClass}`} key={index}>
             //rest of your code

```

you'll have a dynamic background based on the temperatures!
